classifier_type: ["linear_svm", "logreg", "rbf_svm"]
embeddings_weights:
  - [0.1, 0.3, 0.6]
  - [0.2, 0.3, 0.5]
  - [0.3, 0.2, 0.5]
feature_drop:
  - []                 # none
  - ["PR"]
  - ["SR"]
  - ["HS"]
  - ["UL"]
  - ["SP", "NC"]
